#!/bin/bash
# Generates ~/Applications/Finance Tracker.app - a Dock-clickable launcher
# for the local dashboard server (same "shell script wearing a .app
# bundle" trick as this user's other project, Orca Profile Manager: no
# compiled binary, just Info.plist pointing CFBundleExecutable at a shell
# script). Re-run any time after moving the project to bake in the new path.
#
# Usage:
#   bash scripts/install-macos-app.sh

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$HOME/Applications/Finance Tracker.app"
CONTENTS="$APP_DIR/Contents"

mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"

# Build AppIcon.icns from assets/icon.png (source of truth, versioned in the repo)
ICON_SRC="$PROJECT_DIR/assets/icon.png"
if [ -f "$ICON_SRC" ]; then
  ICONSET_DIR="$(mktemp -d)/AppIcon.iconset"
  mkdir -p "$ICONSET_DIR"
  for size in 16 32 128 256 512; do
    sips -z "$size" "$size" "$ICON_SRC" --out "$ICONSET_DIR/icon_${size}x${size}.png" >/dev/null
    double=$((size * 2))
    sips -z "$double" "$double" "$ICON_SRC" --out "$ICONSET_DIR/icon_${size}x${size}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET_DIR" -o "$CONTENTS/Resources/AppIcon.icns"
  rm -rf "$(dirname "$ICONSET_DIR")"
fi

cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>launch.sh</string>
    <key>CFBundleIdentifier</key>
    <string>com.financetracker.app</string>
    <key>CFBundleName</key>
    <string>Finance Tracker</string>
    <key>CFBundleDisplayName</key>
    <string>Finance Tracker</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleIconName</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

cat > "$CONTENTS/MacOS/launch.sh" <<LAUNCH
#!/bin/bash
# Generated by scripts/install-macos-app.sh - re-run that script instead of
# editing this file directly, it gets overwritten.

PROJECT_DIR="$PROJECT_DIR"
PORT=8787

port_up() { curl -s -o /dev/null "http://127.0.0.1:\$1"; }

if ! port_up "\$PORT"; then
  cd "\$PROJECT_DIR"
  source .venv/bin/activate
  nohup python -m scripts.serve_dashboard > /tmp/finance-tracker-server.log 2>&1 &
  for i in \$(seq 1 20); do
    port_up "\$PORT" && break
    sleep 0.5
  done
fi

open "http://127.0.0.1:\$PORT/"
LAUNCH

chmod +x "$CONTENTS/MacOS/launch.sh"

echo "Installed: $APP_DIR"
echo "Drag it onto the Dock from ~/Applications to finish."
